#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

versionFilePath = "#{File.expand_path("..", __dir__)}/.version"
version = File.read(versionFilePath).strip

system("gem build #{File.expand_path("..", __dir__)}/ZReviewTender.gemspec")
system("gem push #{File.expand_path("..", __dir__)}/ZReviewTender-#{version}.gem")
File.delete("#{File.expand_path("..", __dir__)}/ZReviewTender-#{version}.gem")